name: FriendSystemGUI
version: '${project.version}'
main: me.sk8ingduck.friendsystemgui.FriendSystemGUI
authors: [ sk8ingDuck ]

softdepend:
  - PlaceholderAPI

commands:
  f:
    description: open friend menu
    usage: /f
  forwardcmd:
    description: Forward a Bukkit command to Bungeecord
    usage: /forwardcmd <Command>
